### ISSUE TITLE
`Numerical optimization failed` for smoothest path in R4.3+

### ISSUE THREAD

**Issue by MosesStewart** [JMSLab/eventstudyr#41] opened 2023-06-21 23:10 UTC
In the attached example code [`eventstudyr_issue.zip`](https://github.com/JMSLab/eventstudyr/files/11826864/eventstudyr_issue.zip), the smooth path optimization is failing with the example data. Specifically, I see a message that says:
```
Error in FindCoeffs(res_order, coefficients, inv_covar, Wcritic, pN, order,  : 
  Numerical optimization failed when searching for the smoothest path. Please set 'Smpath' to FALSE.
```

I am using `R 4.3.0` on Windows 11.

_code is written below_
```
main <- function() {
    estimates_ols <- EventStudy(
        estimator = "OLS",
        data = example_data,
        outcomevar = "y_jump_m", policyvar = "z",
        idvar      = "id",       timevar   = "t",
        controls = "x_r",
        post = 5, overidpost = 2,
        pre  = 0,  overidpre = 6
    )

    y_breaks = seq(-1, 2, 1)
    plts <- list()

    plts[["smooth_path"]] <- EventStudyPlot(estimates         = estimates_ols,
                                            pre_event_coeffs  = FALSE,
                                            post_event_coeffs = FALSE,
                                            ybreaks           = y_breaks,
                                            smpath            = TRUE) +
                                theme_plots()
}

main()
```

**Comment by jmshapir** [comment] 2023-06-26 13:28
@MosesStewart actually I had a different thought.

See below for my output when I run the snippet in R 4.2.2.

I don't seem (?) to hit an error in computing the smoothest path. (There is an error with `theme_plots` but I don't think that's related to `eventstudyr`.)

Do you want to see what happens if you rewind to R 4.2.2 and try this again? (It's possible that [Anaconda](https://docs.anaconda.com/free/anaconda/packages/using-r-language/) might help you maintain multiple versions of R without having to uninstall.)

If at that point you don't get an error then we've likely isolated the issue to a change in base R. If you do get the error then something else must differ between our setups.

(If I have a chance I'll also try updating my R installation to see if I can reproduce the error that way.)

Thank you!

```
> source("eventstudyr_issue/evenstudyr_issue.r")

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

data.table 1.14.8 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com

Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last

Smoothest path note: The lowest order such that a polynomial is in confidence region is 8.
Error in theme_plots() : could not find function "theme_plots"
In addition: Warning messages:
1: package ‘ggplot2’ was built under R version 4.2.3 
2: package ‘ggthemes’ was built under R version 4.2.3 
3: package ‘eventstudyr’ was built under R version 4.2.3 
```

**Comment by MosesStewart** [comment] 2023-06-26 20:03
> Do you want to see what happens if you rewind to R 4.2.2 and try this again? (It's possible that [Anaconda](https://docs.anaconda.com/free/anaconda/packages/using-r-language/) might help you maintain multiple versions of R without having to uninstall.)

@jmshapir I was able to uninstall and reinstall `R 4.2.3` and it worked! I think the function is only failing for `R 4.3+`. Thank you for the troubleshooting help!

**Comment by jmshapir** [comment] 2023-06-28 11:41
Update: When time permits @MosesStewart is going to take a look at the source of the bug.

@MosesStewart when you're ready to start work here please let me know and I will elevate your permissions.

Thanks!

**Comment by jmshapir** [comment] 2023-06-28 13:48
@MosesStewart you now have write permission to the repo. Use it wisely!

@rcalvo12 @nateschor @ew487 fyi

**Comment by jmshapir** [comment] 2023-07-10 19:50
Per call: @MosesStewart will take the lead on debugging and will reach out to @nateschor for assistance if needed.

**Comment by jmshapir** [comment] 2023-10-05 22:08
@cindyjulianelu once you accept the invite to join the repository please let me know and I will assign you here thanks!

**Comment by cindyjulianelu** [comment] 2023-10-06 10:21
ok I'm in @jmshapir

**Comment by SimonFreyaldenhoven** [comment] 2023-10-06 11:37
@nateschor would you still be able to help @cindyjulianelu if she has any questions and potentially review the fix she comes up in this issue?

**Comment by jmshapir** [comment] 2023-10-06 12:18
> ok I'm in @jmshapir

Welcome @cindyjulianelu!

Can you please review the documents [here](https://github.com/JMSLab/Template/tree/380e12f4d8cb94165fd9f86262894780b008be1e/docs) and pay special attention to to the storage principles?

Once you've reviewed these, please let me know and I can elevate your permissions to allow you to push to the repository.

Thanks!

@SimonFreyaldenhoven fyi

**Comment by nateschor** [comment] 2023-10-09 22:38
@SimonFreyaldenhoven hi! Can @santiagohermo review instead (if you're able to) since Santiago wrote the smoothest path code and is more familiar with it?

**Comment by jmshapir** [comment] 2023-10-09 22:48
I'm guessing @santiagohermo is tied up for at least the next several weeks. Happy to watch the thread here and do my best to answer questions if I can.

**Comment by santiagohermo** [comment] 2023-10-09 23:21
Thanks @nateschor @jmshapir! Indeed, I have some heavy weeks ahead. If this is still open later on and I can be of help, happy to take a look then.

**Comment by cindyjulianelu** [comment] 2023-10-11 12:36
Works for me! I'll be on the slow grind since I also suddenly got busy. Nice to e-meet you @santiagohermo

**Comment by jmshapir** [comment] 2023-10-17 12:55
@cindyjulianelu thanks!

Can you please take a look at the principles [here](https://github.com/JMSLab/Template/blob/881d0be62ff18572aa76a0644b25b50c71eae7de/docs/readme.md) and confirm that these docs, and in particular the storage principles, are clear to you?

At that point I can elevate your permissions to allow you to push to the repo.

Thank you!

**Comment by cindyjulianelu** [comment] 2023-10-17 14:13
Yea but I'm finding myself quite confused over expectations because I did delve through all the resources, even the long document about social science best practices. It took a while because I was also trying to match that file organization structure to this repo's but looks different. Also Simon told me at out meeting to just start on it as soon as possible with creating a branch.

**Comment by jmshapir** [comment] 2023-10-17 14:31
@cindyjulianelu thanks for clarifying! Probably the most important things for you to understand are the storage principles [here](https://github.com/JMSLab/Template/blob/881d0be62ff18572aa76a0644b25b50c71eae7de/docs/storage.md#file-types-and-sizes) (including the warning at the bottom) and the workflow [here](https://github.com/JMSLab/Template/blob/881d0be62ff18572aa76a0644b25b50c71eae7de/docs/workflow.md).

If those are clear to you please let me know.

@SimonFreyaldenhoven fyi.

**Comment by jmshapir** [comment] 2023-10-17 17:14
@cindyjulianelu your permissions have been elevated! Please use it wisely.

**Comment by jmshapir** [comment] 2023-10-23 20:32
Per call, let's:
* Move ephemeral code to `/issue` subfolder 
* Plot (i) Wald region, (ii) Wald region + polynomial at starting value for solver, (iii) Wald region + polynomial at ending value for solver.

**Comment by cindyjulianelu** [comment] 2023-11-30 16:20
A bit boggled but trying a few things right now as we speak - 
Pretty much explored increasing the tolerance for the Nelder Mead numeric optimization method in R. But the objective function value (R parameter) that's spit out from the optimization doesn't match the square of the last coefficient of the "par" vector (just a name R gives in its output, see below) 

![image](https://github.com/JMSLab/eventstudyr/assets/20672288/a2ff010c-2aa6-4bd7-b9ad-8dbf329f1283)

**Comment by jmshapir** [comment] 2023-12-01 01:17
@SimonFreyaldenhoven thanks! That makes sense.

Would it help in a case like this just to set the default maximum polynomial order to something lower (e.g. 5)?

https://github.com/JMSLab/eventstudyr/blob/04691ee6beb5815114f0dabb285794e7291a3bf7/R/AddSmPath.R#L19

**Comment by jmshapir** [comment] 2023-12-02 18:41
@SimonFreyaldenhoven another thought I have in this direction is that we could also set an adaptive default that, e.g., sets the maximum polynomial order to some given fraction of the length of the plotting window. That would account for the fact that the polynomial is likely to become naturally more complex with longer windows.

Let me know what you think thanks.

**Comment by SimonFreyaldenhoven** [comment] 2023-12-04 15:30
@jmshapir Thanks!

Making the polynomial order a function of the horizon might be a bit awkward: Conceptually, I'd say we want (need) a higher order for the "same smoothness" as we extend the horizon. But computationally my guess is that the problem becomes harder for a fixed order polynomial as we increase the horizon.

Lower polynomials will indeed be easier. So limiting the max_order is one option. Regardless, updating the solver and increasing the tolerance should be helpful too, @cindyjulianelu should have a few numbers ready for us to look at before our meeting later.

**Comment by cindyjulianelu** [comment] 2023-12-04 15:51
![image](https://github.com/JMSLab/eventstudyr/assets/20672288/70b515fe-910e-41c9-b9b2-501763fe4474)
[Uploading result_tbl_12-4-23.csv…]()

**Comment by jmshapir** [comment] 2023-12-04 20:43
Per call, let's:
* Look at some pictures and see if looser tolerances lead to reasonable solutions
  * If so, loosen default tolerance
  * If not, add a "second step" in which the code tries a looser tolerance if it fails

**Comment by SimonFreyaldenhoven** [comment] 2023-12-14 16:44
@jmshapir @chansen776 @jorpppp 

below are the 6 different runs from the table above, with the original on the LHS, and a reduced tolerance on the RHS. 

(In the case of the first one - which returned an error before - @cindyjulianelu jsut grabbed the current value at the last iteration before the solver failed out with an error)

They look pretty similar, and a  lower tolerance tends to be "better" in a numerical sense than the alternative algorihtms we tried. 

So my vote is to just reduce the relative tolerance. @jmshapir @chansen776 @jorpppp let me know if that sounds good to you!

This tolerance is imposed on the square of the highest order polynomial coefficient. In the figure below, we went from 1e-8 to 1e-3. @cindyjulianelu also tried 1e-4, which also converges everywhere and looks pretty much identical to the RHS shown below. Either is fine with me. Perhaps 1e-4 is "nice" because it effectively states that we go until the improvement in the highest order coefficient is less than 1 percent.

![image](https://github.com/JMSLab/eventstudyr/assets/20975521/6128950d-3b9c-4925-974e-4f27adc4238c)
![image](https://github.com/JMSLab/eventstudyr/assets/20975521/1fb9af5c-7615-491d-a15a-bcbc1d931060)

@cindyjulianelu Feel free to chime in if I misrepresented any of your results above!

**Comment by cindyjulianelu** [comment] 2023-12-14 21:27
All good @SimonFreyaldenhoven and hope one of these solutions is chosen

**Comment by jmshapir** [comment] 2023-12-15 16:13
@SimonFreyaldenhoven thanks!

I think you mean increase rather than reduce the (magnitude of) the default tolerance?

In any case I am fine with changing it and agree that `1e-4` sounds like a good benchmark.

@SimonFreyaldenhoven can you make the change and then open a pull request here with @jmshapir as the reviewer?

**Comment by SimonFreyaldenhoven** [comment] 2023-12-15 21:34
@jmshapir will do!and yes, I of course meant increase!

@cindyjulianelu On a quick glance, it looks like this would only involve changing lines 117 and 124 in [SmPathHelpers.R](https://github.com/JMSLab/eventstudyr/blob/41-smoothest-path-r-4-3-1/R/SmPathHelpers.R), also see below:
![image](https://github.com/JMSLab/eventstudyr/assets/20975521/a67f9ba3-9c73-44e8-ab67-51798fe6a22b)

Does that sound right to you?

**Comment by cindyjulianelu** [comment] 2023-12-16 12:48
Yes that's right @Simon ***@***.***>
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmshapir** [comment] 2023-12-18 18:16
[issue subfolder for merged issue branch](https://github.com/JMSLab/eventstudyr/tree/f8178ece4fc6fc528f8d386fa4c9e343f3d91af8/issue)

**Closed** 2023-12-18 18:19 UTC
