### ISSUE TITLE
Update version and release

### ISSUE THREAD

**Issue by santiagohermo** [JMSLab/eventstudyr#39] opened 2023-05-22 22:04 UTC
In this issue we will

- Create a branch to update the version number in DESCRIPTION
- Create a new release
- [x] check for [reverse dependencies](https://r-pkgs.org/release.html#sec-release-revdep-checks)
- [x] update the [comments for CRAN](https://r-pkgs.org/release.html#sec-release-cran-comments)  

We will also discuss a new submission to CRAN.

**Comment by nateschor** [comment] 2023-05-23 16:29
### Version Number

Replying to https://github.com/JMSLab/eventstudyr/pull/38#issuecomment-1558064853 from @jmshapir and @santiagohermo:

I say we go to `1.1.0` since we [add functionality](https://github.com/JMSLab/eventstudyr/issues/31#issuecomment-1558018165) to `EventStudy()` in a [backwards compatible way](https://semver.org/). How does incrementing the minor number sound?

### Submitting to CRAN

The second to last bullet in the **Submission** section of the [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html) says that: "Submitting updates should be done responsibly and with respect for the volunteers’ time. Once a package is established (which may take several rounds), “no more than every 1–2 months” seems appropriate."

We last submitted a little over a month ago on [April 19](https://github.com/JMSLab/eventstudyr/issues/33#issuecomment-1514155373), but as @jmshapir pointed out during our last call, it seems reasonable to expect more frequent changes at the beginning of a package's lifecycle and then less frequent changes as the package matures. I also don't know that the 1-2 months applies to us, because I'm not sure we're an "established package" (yet :)). I am in favor of submitting to CRAN!

### Proposed Next Steps
1. Update version number
2. Merge changes in this issue into main (the only change should be the new version number)
3. Create a new release (with the same version number from step 1)
4. Submit to CRAN
     a. If our updated submission gets rejected, we'll have to make the changes and update the patch number. I don't think it will be worth it to make a new release for making a small tweak, but we should increment our version number for CRAN to signal that we have made their changes. In this case, our CRAN version number will be greater than our GitHub release number 

@jmshapir @santiagohermo @ew487 please feel free to adjust the next steps, thanks!

**Comment by jmshapir** [comment] 2023-05-23 18:07
@nateschor thanks! All sounds good to me except I'm in favor of keeping our github release version synchronized with our CRAN version.

One approach could be to do steps (1) and (4) and then wait for CRAN acceptance before we do (2) and (3).

**Comment by nateschor** [comment] 2023-05-24 21:26
Just an update that I should have time tomorrow or Friday to wrap this issue up and open a PR, thanks!

**Comment by nateschor** [comment] 2023-05-26 16:39
@ew487 @santiagohermo I'm trying to use the [revdepcheck](https://revdepcheck.r-lib.org/) package described [here](https://r-pkgs.org/release.html#sec-release-revdep-checks) to test for the (unlikely) event that any other R packages have taken an `eventstudyr` dependency. As you can see in the `## R CMD Check Results` comment block [here](https://r-pkgs.org/release.html#sec-release-cran-comments), we'll want to include the output of running `revdepcheck` in our `cran-comments.md` file.

When I try installing the package as suggested in the [documentation](https://revdepcheck.r-lib.org/) with `devtools::install_github('r-lib/revdepcheck')`, I get the error message below since not all of my packages are up to date. I'm hesitant to start updating my packages since that usually results in code breaking.

<details><summary>Error Message</summary>
<p>

```r
* installing *source* package 'revdepcheck' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'cli' 3.0.1 is being loaded, but >= 3.1.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'revdepcheck'
* removing 'C:/Users/c1nhs01/R/win-library/4.0/revdepcheck'
Warning messages:
1: In utils::install.packages(pkgs = pkgs, lib = lib, repos = myrepos,  :
  installation of package ‘C:/Users/c1nhs01/AppData/Local/Temp/RtmpsPltRs/file98452d733c1/revdepcheck_1.0.0.9001.tar.gz’ had non-zero exit status
2: In utils::install.packages(pkgs = pkgs, lib = lib, repos = myrepos,  :
  installation of package ‘C:/Users/c1nhs01/AppData/Local/Temp/RtmpsPltRs/file98452d733c1/revdepcheck_1.0.0.9001.tar.gz’ had non-zero exit status
``` 

</p>
</details> 

Would one of you be able to try installing the package and running `revdepcheck::revdep_check(num_workers = 4)`?

Thank you!

**Comment by nateschor** [comment] 2023-05-26 16:49
@santiagohermo thanks for writing up the release! 

Can you confirm whether or not the steps below are the proper way to make edits?
1. Make a change. For example, in the screenshot, changing `1.x.x` to `1.1.0` and changing "first" to "most recent"
2. Select "Set as the latest release"
3. Click "Save draft"

Thank you!

<details><summary>Screenshot of Release</summary>
<p>

![image](https://github.com/JMSLab/eventstudyr/assets/70981003/56466192-5a7a-49bd-9779-4c5ded06f259)

</p>
</details>

**Comment by santiagohermo** [comment] 2023-05-26 18:13
Thanks @nateschor! 

- On [revdepcheck](https://github.com/JMSLab/eventstudyr/issues/39#issuecomment-1564650759). I installed the package and ran `revdepcheck::revdep_check(num_workers = 4)`. This is the output:

  ![image](https://github.com/JMSLab/eventstudyr/assets/45404755/7e6de32b-5815-4424-801c-354e7c94c043)

  The command created a `/revdep/` folder that weights ~ 270 MB. These are the main md files: [revdep.zip](https://github.com/JMSLab/eventstudyr/files/11578746/revdep.zip)
 

- On [editing the release](https://github.com/JMSLab/eventstudyr/issues/39#issuecomment-1564660932). The procedure you describe sounds good! The "Set as the latest release" checkbox should be selected by default.

**Comment by nateschor** [comment] 2023-05-30 16:46
Thanks @santiagohermo!

I'm not sure if `revdepcheck` worked as we're expecting it too? From [here](https://r-pkgs.org/release.html#sec-release-cran-comments), you can see that the function checked 231 reverse dependencies. 

I opened `cran.md` from [revdep.zip](https://github.com/JMSLab/eventstudyr/files/11578746/revdep.zip) (shown below), and it says that 0 reverse dependencies were checked. My reading of that is we didn't actually check any packages, but maybe it means that we don't have any reverse dependencies at the moment?

Thanks!

![image](https://github.com/JMSLab/eventstudyr/assets/70981003/95354226-bc8c-422e-b576-85c66d8e0623)

**Comment by jmshapir** [comment] 2023-05-30 18:59
@nateschor I think a [reverse dependency](https://stackoverflow.com/questions/29567584/what-are-reverse-dependencies-in-r) is a package that depends on `eventstudyr`. If that's right it makes sense to me that there would be none (so far!). And it seems like there is [precedent](https://rdrr.io/github/r-lib/sloop/f/cran-comments.md) for 0 reverse dependencies.

If we're not seeing any errors or warnings with `revdepcheck` and everything else is ready to go, maybe it's simplest to submit and address any issues that arise after submission?

@SimonFreyaldenhoven fyi.

**Comment by nateschor** [comment] 2023-05-30 19:30
> @nateschor I think a [reverse dependency](https://stackoverflow.com/questions/29567584/what-are-reverse-dependencies-in-r) is a package that depends on `eventstudyr`. If that's right it makes sense to me that there would be none (so far!). And it seems like there is [precedent](https://rdrr.io/github/r-lib/sloop/f/cran-comments.md) for 0 reverse dependencies.

@jmshapir this explanation matches my understanding! I wasn't sure if "We checked 0 reverse dependencies" means that the function checked and found 0 reverse dependencies, or the function wasn't working probably and wasn't able to run any checks, meaning it checked 0 other packages.

> If we're not seeing any errors or warnings with `revdepcheck` and everything else is ready to go, maybe it's simplest to submit and address any issues that arise after submission?

This sounds good to me! I'll work on wrapping this issue up and then opening a PR

**Comment by nateschor** [comment] 2023-06-12 15:31
## Summary

In this issue, version `1.1.1` was accepted to [CRAN](https://github.com/JMSLab/eventstudyr/pull/40#issuecomment-1584763236). 

* We were initially rejected from CRAN since the URLs in our `README` were not in the [canonical](https://github.com/JMSLab/eventstudyr/pull/40#issuecomment-1573803835) CRAN form
* Set a [seed](https://github.com/JMSLab/eventstudyr/pull/40/commits/66070e3ecd301d9ae7644adeba0820637e67dade) to make our `README` plot reproducible 
* Ran [reverse dependency checks](https://github.com/JMSLab/eventstudyr/issues/39#issuecomment-1564751833), which will be important if any future R packages take `eventstudyr` as a dependency

Stable link to issue branch [here](https://github.com/JMSLab/eventstudyr/tree/66070e3ecd301d9ae7644adeba0820637e67dade)

Merged into main in

**Closed** 2023-06-12 15:31 UTC
